name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the build whenever you push to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material # Installs mkdocs and the material theme

      - name: Build and Deploy
        run: |
          mkdocs gh-deploy --force